name: Mi primer workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Imprimir mensaje
        run: echo "Hola, GitHub Actions está vivo! 🚀"
      - name: If develop branch
        if: github.ref == 'refs/head/develop'
        run: echo "This is the develop branch" 
      - name: is master branch
        run: echo "hola"